services:
  # Service Base de Données
  # Nous utilisons l'image officielle pgvector pour avoir PostgreSQL 16 + l'extension vectorielle pré-installée.
  postgres:
    image: pgvector/pgvector:pg16
    container_name: techwatch-postgres
    ports:
      - "5432:5432" # Expose le port par défaut pour tes outils locaux (DBeaver, etc.)
    environment:
      - POSTGRES_USER=techwatch
      - POSTGRES_PASSWORD=techwatchpass
      - POSTGRES_DB=techwatchdb
    volumes:
      # Persistance des données : si tu éteins le conteneur, les données restent.
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Cette commande permet à Docker de savoir si la base est "prête" à recevoir des connexions
      test: ["CMD-SHELL", "pg_isready -U techwatch -d techwatchdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - techwatch-network

# Définition des volumes persistants
volumes:
  postgres_data:

# Définition d'un réseau dédié pour que nos futurs conteneurs (Java, Python) puissent se parler
networks:
  techwatch-network:
    driver: bridge